spring.datasource.url=${SUPABASE_JDBC_URL}
spring.datasource.username=${SUPABASE_DB_USER}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=false

file.upload.directory=/tmp/uploads
